trainer_name: pytorch-lightning-trainer
corpus_manager: pytorch-lightning-corpus
huggingface_model: "FacebookAI/roberta-large"
batch_size: 32
learning_rate: 2e-5
weight_decay: 0.01
max_epochs: 50
num_workers: 4
device: gpu
early_stopping_delta: 0.0005
early_stopping_patience: 5
label_smoothing: 0
model: "trf_ffn"