defaults:
  - data: conll2003
  - teacher: k_means
  - trainer: spacy_ner
  - mlflow: localhost
  - experiment: ner
  - converter: spacy
  - technical: default
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom
