defaults:
  - data: conll2003
  - teacher: margin_confidence
  - trainer: pytorch_lightning
  - mlflow: localhost
  - experiment: ner
  - converter: pass_through
  - technical: default
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom
